name: template-init
on:
  push:
    branches: [main]
jobs:
  template-init:
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'template-java' # Only run when the repo is not template-java
    permissions:
      contents: write
    steps:
      # Checkout source code
      - name: Fetch Sources
        uses: actions/checkout@v3
      # Cleanup
      - name: Cleanup
        run: |
          export LC_CTYPE=C
          export LANG=C
          
          # Prepare variables
          NAME="${GITHUB_REPOSITORY##*/}"
          OWNER="${GITHUB_REPOSITORY%%/*}"
          
          # Code tolerant strings
          SAFE_NAME=$(echo $NAME | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          SAFE_OWNER=$(echo $OWNER | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          
          # Remove non-sense files
          rm -rf \
            .github/workflows/template-init.yml \
            .github/README.md
          
          # Remove annoying files when the repo is not for me
          if [[ "$OWNER"x != "imkiva"x ]]; then
            rm -rf \
              .github/CODE_OF_CONDUCT.md \
              .github/workflows/commit-check.yml \
              .github/workflows/commit-check.sh
            sed -i "s/dev(\"imkiva\", \"Kiva Oyama\", \"imkiva@islovely.icu\")//g" build.gradle.kts
          fi
          
          # Move contents
          sed -i "s/template/$NAME/g" settings.gradle.kts
          sed -i "s/org.imkiva/org.$SAFE_OWNER/g" build.gradle.kts
          sed -i "s|https://github.com/imkiva/template|$GITHUB_SERVER_URL/$GITHUB_REPOSITORY|g" build.gradle.kts
          mv template "$NAME"

      # Commit modified files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "init: template cleanup"
      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
